import os, sys
from pygame.math import Vector2

DIRECTORY = os.path.dirname(__file__).removesuffix("\code").removesuffix("/code")

if sys.platform == "darwin":
    SCREEN_WIDTH, SCREEN_HEIGHT = 1200, 800
    OS_IS_MAC = False
    SIZE_MULTIPLIER = 1.5
    BUTTON_FACTOR = 6
else:
    SCREEN_WIDTH, SCREEN_HEIGHT = 1500, 1000
    OS_IS_MAC = False 
    SIZE_MULTIPLIER = 1.5
    BUTTON_FACTOR = 8

HALF_SCREEN_WIDTH, HALF_SCREEN_HEIGHT = (SCREEN_WIDTH/2), (SCREEN_HEIGHT/2)

SCREEN_VECTOR = Vector2(SCREEN_WIDTH, SCREEN_HEIGHT)
CENTER_VECTOR = Vector2(HALF_SCREEN_WIDTH, HALF_SCREEN_HEIGHT)

BOUND_BOX_FACTOR = SCREEN_WIDTH / 1280
BOUND_BOX_DIMENSIONS = Vector2(836, 436) * BOUND_BOX_FACTOR

BUTTON_PIXEL_WIDTH, BUTTON_PIXEL_HEIGHT = 35, 14

PLAYER_SIZE = Vector2(24, 24)
PLAYER_HP = 5
PLAYER_INVULNERABILITY_COUNT = 90

SCREEN_FPS = 60

MOVEMENT_SPEED = 2
ROTATION_SPEED = 8
ACCELERATION_RATE = 0.8
ACCELERATION_LIMIT = 1.1
DECCELLERATION_RATE = 0.935
BOUNCE_DECCELLERATION = 0.90

STAGE_COUNTS = [120, 1500, 4800]

ORB_ANIMATION_INTERVAL = 400
ORB_SPEED = 1.6